// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Customer = { id: number, name: string, phone: string, address: string, notes: string, };