// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expense } from "./Expense";

export type ExpenseReport = { start_date: string, end_date: string, expenses: Array<Expense>, total_expenses: string, };