// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExpenseReportFilter } from "./ExpenseReportFilter";

export type ExpenseReportRequest = { start_date: string, end_date: string, filters: Array<ExpenseReportFilter>, };