// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { User } from "./User";

export type Expense = { id: number, date_time: string, description: string, created_by_user: User, amount: string, };