// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InventoryItem = { id: number, name: string, price: string, stock: number, quantity_per_box: number, };