// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InventoryItemPatchRequest = { name: string | null, description: string | null, 
/**
 * A decimal number with a precision of 2 decimal places
 */
price: string | null, stock: number | null, quantity_per_box: number | null, };