// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterOperator } from "./FilterOperator";
import type { SortOrder } from "./SortOrder";
import type { SqlType } from "./SqlType";

export type InventoryItemListRequest = { range: { 
/**
 * Number of items to send
 */
count: number, 
/**
 * First item's index
 */
offset: number, }, sorts: Array<{ column: string, order: SortOrder, }>, filters: Array<{ column: string, operator: FilterOperator, value: SqlType, }>, };