// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InventoryItemPostRequest = { name: string, description: string, 
/**
 * A decimal number with a precision of 2 decimal places
 */
price: string, stock: number, quantity_per_box: number, };