// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserPermissionVec } from "./UserPermissionVec";

export type ListUserData = { username: string, permissions: UserPermissionVec, };