// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ListRange = { 
/**
 * Number of items to send
 */
count: number, 
/**
 * First item's index
 */
offset: number, };