// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterOperator } from "./FilterOperator";
import type { SqlType } from "./SqlType";

export type ListFilter = { column: string, operator: FilterOperator, value: SqlType, };