// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ListFilter } from "./ListFilter";
import type { ListRange } from "./ListRange";
import type { ListSort } from "./ListSort";

export type ListRequest = { range: ListRange, sorts: Array<ListSort>, filters: Array<ListFilter>, };