// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Setting } from "./Setting";

export type MultipleSettingsRequest = Array<Setting>;