// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Customer } from "./Customer";
import type { User } from "./User";

export type OrderMeta = { id: number, date_time: string, 
/**
 * This will be false if the order is retail
 */
customer: Customer | null, created_by_user: User, amount_paid: string, retail: boolean, notes: string, };