// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrderItemPatchRequest } from "./OrderItemPatchRequest";

export type OrderPatchRequest = { customer_id: number | null, retail: boolean | null, notes: string | null, amount_paid: string | null, items: Array<OrderItemPatchRequest>, };