// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrderReportFilter } from "./OrderReportFilter";

export type OrderReportRequest = { start_date: string, end_date: string, filters: Array<OrderReportFilter>, };