// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OrderItemPatchRequest = { inventory_item_id: number | null, quantity: number | null, price: string | null, };