// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Order } from "./Order";

export type OrderReport = { start_date: string, end_date: string, orders: Array<Order>, total_revenue: string, total_receivable: string, };