// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OrderPostRequest = { customer_id: number | null, retail: boolean, notes: string, amount_paid: string, fulfilled: boolean, };