// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OrderItemUpdateRequest = { 
/**
 * If the id is None, a new item will be created
 * If the id is Some, the item with that id will be updated
 */
order_item_id: number | null, inventory_item_id: number, quantity: number, price: string, discount: string, discount_percentage: boolean, };