// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Customer } from "./Customer";
import type { OrderItem } from "./OrderItem";
import type { User } from "./User";

export type Order = { items: Array<OrderItem>, id: number, date_time: string, 
/**
 * This will be false if the order is retail
 */
customer: Customer | null, created_by_user: User, amount_paid: string, retail: boolean, retail_customer_name: string | null, retail_customer_phone: string | null, retail_customer_address: string | null, fulfilled: boolean, notes: string, };