// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OrderItemPostRequest = { inventory_item_id: number, quantity: number, price: string, };