// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrderItem } from "./OrderItem";
import type { OrderMeta } from "./OrderMeta";

export type Order = { meta: OrderMeta, items: Array<OrderItem>, };