// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Customer } from "./Customer";
import type { OrderMeta } from "./OrderMeta";
import type { Supplier } from "./Supplier";

export type PaymentParty = { "Customer": Customer } | { "Supplier": Supplier } | { "Retail": OrderMeta };