// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaymentMethod } from "./PaymentMethod";
import type { PaymentParty } from "./PaymentParty";
import type { TransferType } from "./TransferType";
import type { User } from "./User";

export type Payment = { id: number, date_time: string, amount: string, party: PaymentParty, transfer_type: TransferType, method: PaymentMethod, method_details: string, notes: string, created_by_user: User, };