// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PublicInventoryItem = { id: number, name: string, 
/**
 * A decimal number with a precision of 2 decimal places
 */
price: string, quantity_per_box: number, };