// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InventoryItem } from "./InventoryItem";

export type PurchaseItem = { id: number, inventory_item: InventoryItem, quantity: number, price: string, };