// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PurchaseItemUpdateRequest = { 
/**
 * The ID of the inventory item
 * If this is set, the inventory item will be updated
 * If this is not set, the inventory item will be created
 */
purchase_item_id: number | null, inventory_item_id: number, quantity: number, price: string, };