// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PurchasePatchRequest = { supplier_id: number | null, notes: string | null, amount_paid: string | null, date_time: string | null, };