// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Supplier } from "./Supplier";
import type { User } from "./User";

export type PurchaseMeta = { id: number, created_by_user: User, supplier: Supplier, date_time: string, };