// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReportFilters = { customer_id: number | null, product_id: number | null, user_id: number | null, };