// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReportFilter } from "./ReportFilter";
import type { ReportRequestType } from "./ReportRequestType";

export type ReportRequest = { start_date: string, end_date: string, filters: Array<ReportFilter>, report_types: Array<ReportRequestType>, };