// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expense } from "./Expense";
import type { Order } from "./Order";
import type { ReportRequestType } from "./ReportRequestType";

export type Report = { start_date: string, end_date: string, orders: Array<Order>, expenses: Array<Expense>, purchases: Array<[null, null]>, data: { [key: ReportRequestType]: string }, };