// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * If neither column nor nested_access is provided, the search will be done on id
 */
export type SearchRequest = { search: string, column: string | null, count: number, 
/**
 * Access nested columns using dot notation
 * customers.name
 * This will mean that column is disregarded
 * NOTE: Nested access only works if the tables are
 * joined in the query. This will happen if there is a foreign key
 * relationship between the tables.
 */
nested_access: string | null, };