// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SettingType = { "Boolean": boolean } | { "Text": string } | { "Int": number } | { "Float": number } | { "UnsignedInt": number } | { "Decimal": string } | { "TextVec": Array<string> };