// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SettingValueType = "Boolean" | "Text" | "Int" | "Float" | "UnsignedInt" | "Decimal" | "ImageBase64URI" | "TextVec";