// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingType } from "./SettingType";

export type Setting = { key: string, value: SettingType, };