// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StockUpdate = { id: number, date_time: string, inventory_id: number, created_by_user_id: number, delta: number, order_item_id: number | null, order_id: number | null, purchase_item_id: number | null, purchase_id: number | null, };