// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InventoryItem } from "./InventoryItem";

export type StockUpdate = { inventory_item: InventoryItem, delta: number, };