// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserPermission = "PRODUCT_READ" | "PRODUCT_WRITE" | "ORDER_READ" | "ORDER_WRITE" | "MANAGE_DB" | "ADMIN";