// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserPermissionEnum = "INVENTORY_READ" | "INVENTORY_WRITE" | "ORDER_READ" | "ORDER_WRITE" | "MANAGE_DB" | "ADMIN";