// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserPermission } from "./UserPermission";

export type UserPermissionVec = Array<UserPermission>;