// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserPermissionEnum = "INVENTORY_READ" | "INVENTORY_WRITE" | "ORDER_READ" | "ORDER_WRITE" | "CUSTOMERS_READ" | "CUSTOMERS_WRITE" | "SUPPLIERS_READ" | "SUPPLIERS_WRITE" | "EXPENSES_READ" | "EXPENSES_WRITE" | "REPORTS" | "MANAGE_DB" | "ADMIN";