// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserPermissionEnum } from "./UserPermissionEnum";

export type UserPermissionVec = Array<UserPermissionEnum>;